DROP TABLE Customer;
DROP TABLE Location;
DROP TABLE Product;
DROP TABLE Orders;

GO

CREATE TABLE Customer (
	CustomerID INT NOT NULL PRIMARY KEY IDENTITY (100, 1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL
);

CREATE TABLE Product (
	ProductID INT NOT NULL PRIMARY KEY IDENTITY(100, 1),
	Title NVARCHAR(200) NOT NULL,
	Price MONEY NOT NULL
);

CREATE TABLE Location (
	LocationID INT NOT NULL PRIMARY KEY IDENTITY(100, 1),	
	City NVARCHAR(50) NOT NULL,
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(ProductId),
	Quantity INT NOT NULL
);

CREATE TABLE Orders (
	OrderID INT NOT NULL PRIMARY KEY IDENTITY (100, 1),
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
	LocationID INT NOT NULL FOREIGN KEY REFERENCES Location(LocationID),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(ProductId),
	Quantity INT NOT NULL,
	OrderTotal MONEY NOT NULL,
	OrderTime DATETIME NOT NULL
);